version: '3.3'
services:  
  go-boilerplate-api:
    container_name: go-boilerplate-api-container
    restart: always
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        - VERSION=${VERSION}  
        - MONGODB_URL=${MONGODB_URL}  
        - MONGODB_DATABASE=${MONGODB_DATABASE}  
    environment: 
      - VERSION=${VERSION} 
      - MONGODB_URL=${MONGODB_URL} 
      - MONGODB_DATABASE=${MONGODB_DATABASE} 
    ports:
      - '8080:8080' 
    volumes: 
      - ./:/src 